apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws9-portal
  namespace: aws9d
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: www.aws9.pri
    http:
      paths:
      - path: "/shop" #www.aws9.pri/shop
        pathType: Prefix
        backend:
          service:
            name: shop-svc
            port:
              number: 8081
      - path: "/blog"
        pathType: Prefix
        backend:
          service:
            name: blog-svc
            port:
              number: 8081
      - path: "/news"
        pathType: Prefix
        backend:
          service:
            name: news-svc
            port:
              number: 8081