---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-pvc
  namespace: aws9d
spec:
  storageClassName: nginx-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-pvc
spec:
  storageClassName: nginx-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: news-pvc
spec:
  storageClassName: nginx-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  