# SHOP Service
apiVersion: v1
kind: Service
metadata:
  name: shop-svc
  namespace: aws9d
spec:
  selector:
    app: shop
  ports:
    - name: shop
      protocol: TCP
      port: 8081
      targetPort: 80

---
# SHOP Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deploy
  namespace: aws9d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      nodeName: master
      containers:
        - name: shopctn
          image: shop-test:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
            limits: 
              cpu: "200m"
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: shop-pvc

---
# BLOG Service
apiVersion: v1
kind: Service
metadata:
  name: blog-svc
  namespace: aws9d
spec:
  selector:
    app: blog
  ports:
    - name: blog
      protocol: TCP
      port: 8081
      targetPort: 80

---
# BLOG Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deploy
  namespace: aws9d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      nodeName: master
      containers:
        - name: blogctn
          image: blog-test:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
            limits: 
              cpu: "200m"
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: blog-pvc

---
# NEWS Service
apiVersion: v1
kind: Service
metadata:
  name: news-svc
  namespace: aws9d
spec:
  selector:
    app: news
  ports:
    - name: news
      protocol: TCP
      port: 8081
      targetPort: 80

---
# NEWS Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-deploy
  namespace: aws9d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      nodeName: master
      containers:
        - name: newsctn
          image: news-test:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
            limits: 
              cpu: "200m"
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: news-pvc
